# You can put custom rules here
# Window/layer rules: https://wiki.hyprland.org/Configuring/Window-Rules/
# Workspace rules: https://wiki.hyprland.org/Configuring/Workspace-Rules/

# ######## Window rules ########

# Uncomment to apply global transparency to all windows:
# windowrule = opacity 0.89 override 0.89 override, match:class .*

# Disable blur for all xwayland apps
# windowrule = no_blur on, match:xwayland 1
layerrule = match:namespace quickshell:overviewDim, order 5
layerrule = match:namespace quickshell:bar, order 10

# GTK file picker / portal chooser
windowrule = match:class xdg-desktop-portal-gtk, float on, center on, size 900 600

# Common file dialog titles
windowrule = match:title ^Open File$, float on
windowrule = match:title ^Open Folder$, float on
windowrule = match:title ^Save File$, float on
windowrule = match:title ^Save As$, float on

# Login image picker (kdialog)
windowrule = match:title ^Choose login image$, float on, center on, pin on, size 900 600

windowrule {
    name = calamares-by-class
    match:class = ^(io.calamares.calamares)$
    float = on
    suppress_event = fullscreen maximize
    size = 1500 800
    center = on
}
